spring.application.name=weatherapp

# Visual Crossing Weather API Key
weather.api.key=4TMAVXN2VE8HHKCPZBD6Q876F
weather.api.base-url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/

#LOG LEVEL
logging.level.root=DEBUG

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

#To enable the cache logs
logging.level.org.springframework.cache=DEBUG

